export default function Head() {
    return (
        <>
            <title>StayCutios Movies</title>
            <meta content="width=device-width, initial-scale=1" name="viewport"/>
            <meta name="description" content="Generated by StayCutios Movies"/>
            <link rel="icon" href="/favicon.ico"/>
        </>
    )
}
